### PR TITLE
Troubleshooting (GRADED)

### PR DESCRIPTION
**Pull request by wangyb-A**
Exercise 6,
Fix bugs in the troubleshooting document
@thomasbd14

### CODE REVIEW

**Review by thomasbd14 — COMMENTED** [review]
Please knit this and create a separate file

**Comment by SillyPasty** [comment]
Markdown file added in the [commit](https://github.com/stat545ubc-2023/collaborative-group24/pull/12/commits/7e7ac3f637e02755aba93fd677c44d6df8454f1f)

**Comment by wangyb-A** [comment]
> Please knit this and create a separate file

Markdown file added in the [commit](https://github.com/stat545ubc-2023/collaborative-group24/pull/12/commits/7e7ac3f637e02755aba93fd677c44d6df8454f1f)

**Review by thomasbd14 — APPROVED** [review]
Thank you Alex, looks great!

**Pull request merged**
